  ########################################################################

# sudoedit /etc/ssh/sshd_config
# avec sudo ansible-playbook -c local /vagrant/config.vm26.yml
---
- hosts: localhost
  tasks:
    # adresse IPv6 avec nmcli (CLI pour NetworkManager)
    # éventuellement, pour supprimer les connexions en trop, faire
    # $ nmcli connection del ansible-eth1
    - shell: ip route del default
      ignore_errors: True
    - shell: nmcli connection del "Connexion filaire 1"
      ignore_errors: True
    - shell: nmcli connection del "Connexion filaire 2"
      ignore_errors: True
    - shell: nmcli connection del "ansible-eth1"
      ignore_errors: True
    - shell: nmcli connection del "ansible-eth2"
      ignore_errors: True
   
    - shell: nmcli connection add ifname eth1 con-name ansible-eth1 type ethernet ip6 fc00:1234:1::26/64
    - shell: nmcli connection add ifname eth2 con-name ansible-eth2 type ethernet ip6 fc00:1234:2::26/64
    
    
    
    - shell : sysctl -w net.ipv6.conf.all.forwarding=1
