########################################################################
# sudoedit /etc/ssh/sshd_config
# avec sudo ansible-playbook -c local /vagrant/config.vm2.yml
---
- hosts: localhost
  tasks:
  - shell: ip route del default
    ignore_errors: True
  - shell: nmcli connection del "Connexion filaire 1"
    ignore_errors: True
  - shell: nmcli connection del "Connexion filaire 2"
    ignore_errors: True
  - shell: nmcli connection del "ansible-eth1"
    ignore_errors: True
  - shell: nmcli connection del "ansible-eth2"
    ignore_errors: True
      
  
  # IPv4 eth1
  - shell: nmcli connection add ifname eth1 con-name ansible-eth1 type ethernet ip4 172.16.2.132/28
    # IPv4 eth2
  - shell: nmcli connection add ifname eth2 con-name ansible-eth2 type ethernet ip4 172.16.2.162/28
  
    # table de routage
  - shell: sudo ip route add 172.16.2.144/28 via 172.16.2.131
  - shell: sudo ip route add 172.16.2.176/28 via 172.16.2.163
      
  
  
    # IP FORWARD
  - sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes reload=yes
